/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokyo;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author 8531532
 */
public class Connection extends javax.swing.JFrame {

    /**
     * Creates new form Connection
     */
    public Connection() {
        initComponents();
        this.setTitle("Tokyo++ - Connect");
        this.setIconImage(new ImageIcon(getClass()
                .getResource("/img/japan.png"))
                .getImage()); 
        this.setLocationRelativeTo(null);
        
        DatabaseConnection databaseConnection = DatabaseConnection.getInstance();
        
        textFieldIp.setText(databaseConnection.getIp());
        textFieldPort.setText(databaseConnection.getPort());
        textFieldSid.setText(databaseConnection.getSid());
        textFieldUsername.setText(databaseConnection.getUsername());
        textFieldPassword.setText(databaseConnection.getPassword());
        
        labelSuccess.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIp = new javax.swing.JLabel();
        textFieldIp = new javax.swing.JTextField();
        labelPort = new javax.swing.JLabel();
        textFieldPort = new javax.swing.JTextField();
        labelSid = new javax.swing.JLabel();
        textFieldSid = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        textFieldPassword = new javax.swing.JTextField();
        labelSuccess = new javax.swing.JLabel();
        buttonConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelIp.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelIp.setText("IP");

        textFieldIp.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldIp.setText("jTextField1");

        labelPort.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelPort.setText("Port");

        textFieldPort.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldPort.setText("jTextField1");

        labelSid.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelSid.setText("SID");

        textFieldSid.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldSid.setText("jTextField1");

        labelUsername.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelUsername.setText("Username");

        textFieldUsername.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldUsername.setText("jTextField1");

        labelPassword.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelPassword.setText("Password");

        textFieldPassword.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldPassword.setText("jTextField1");

        labelSuccess.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuccess.setText("label");

        buttonConnect.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        buttonConnect.setText("Connect");
        buttonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(labelSid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIp, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(textFieldPort)
                            .addComponent(textFieldSid)
                            .addComponent(textFieldUsername)
                            .addComponent(textFieldPassword)))
                    .addComponent(buttonConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSuccess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnectActionPerformed
        DatabaseConnection databaseConnection = DatabaseConnection.getInstance();
        
        databaseConnection.setIp(textFieldIp.getText());
        databaseConnection.setPort(textFieldPort.getText());
        databaseConnection.setSid(textFieldSid.getText());
        databaseConnection.setUsername(textFieldUsername.getText());
        databaseConnection.setPassword(textFieldPassword.getText());
        
        /* test connection */
        try {
            databaseConnection.getStatement();
            
            labelSuccess.setText("Connection made with success!");
            labelSuccess.setForeground(Color.BLUE);
            labelSuccess.setVisible(true);
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
            labelSuccess.setText("Fail: " + ex.getMessage());
            labelSuccess.setForeground(Color.RED);
            labelSuccess.setVisible(true);
        }
    }//GEN-LAST:event_buttonConnectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnect;
    private javax.swing.JLabel labelIp;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelSid;
    private javax.swing.JLabel labelSuccess;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JTextField textFieldIp;
    private javax.swing.JTextField textFieldPassword;
    private javax.swing.JTextField textFieldPort;
    private javax.swing.JTextField textFieldSid;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
